apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-api-2617
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/auth-api-2617
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
